language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jigglybytez/node-k8s-demo .

after_success:
  - docker build -t jigglybytez/node-k8s-demo
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jigglybytez/node-k8s-demo
